#!/bin/sh

set -e

##libpam-script ve ldap  ayarları varsayılan ayarlara döner
#       if [ -f /usr/share/ahenk/pam_scripts_original/pam_script ]; then

#               cp -fr /usr/share/ahenk/pam_scripts_original/pam_script /usr/share/pam-configs/

#       fi

#       if [ -f /usr/share/ahenk/pam_scripts_original/ldap ]; then

#               cp -fr /usr/share/ahenk/pam_scripts_original/ldap /usr/share/pam-configs/

#       fi


#nsswitch.conf dosyası ayarları
echo "/etc/nsswitch.conf dosyası değişiklikleri kaldırılıyor"
sed -i 's/passwd:         compat ldap/passwd:         compat/g' /etc/nsswitch.conf
sed -i 's/group:          compat ldap/group:          compat/g' /etc/nsswitch.conf
sed -i 's/shadow:         compat ldap/shadow:         compat/g' /etc/nsswitch.conf

echo "Paket ile gelen ayarlar ve dosyalar siliniyor"
rm -rf /usr/share/pam-configs/ldap
rm -rf /usr/share/pam-configs/pam_script
rm -rf /usr/share/lightdm/lightdm.conf.d/99-pardus-xfce.conf
rm -rf /usr/share/ahenk/pam_scripts_original/pam_script
rm -rf /usr/share/ahenk/pam_scripts_original/ldap
DEBIAN_FRONTEND=noninteractive pam-auth-update --package
